### ISSUE TITLE
testnet contracts

### ISSUE THREAD

**Issue by JhonnyJason** [wbobeirne/eth-balance-checker#2]
Hi,
Very awesome Contract!

Is it also deployed on any testnet?

Cheers!

**Comment by wbobeirne** [comment]
Hey @JhonnyJason, I'm sure at some point I did deploy it but I honestly can't remember what the address was 😅 However you can override the default mainnet contract address by passing [`{ contractAddress: '0x...' }`](https://github.com/wbobeirne/eth-balance-checker#library) as the 4th optional parameter should you decide to deploy it yourself.

Feel free to post an address here for others if you do deploy it, otherwise I'm going to continue to leave it up to individuals to do so for their own testing purposes. I'd also be happy to accept PR(s) that update the README with addresses, or provide some kind of "smart" detection of which network you're on and a map of addresses.

**Comment by JhonnyJason** [comment]
Good idea, will do that then ;-) thnx!

**Comment by EvilJordan** [comment]
I have deployed (and verified) to Rinkeby: [0x3183B673f4816C94BeF53958BaF93C671B7F8Cf2](https://rinkeby.etherscan.io/address/0x3183B673f4816C94BeF53958BaF93C671B7F8Cf2)
