### ISSUE TITLE
Bug: invalid argument when fetching native currency balance "0x0"

### ISSUE THREAD

**Issue by itxtoledo** [wbobeirne/eth-balance-checker#45]
Error:

`invalid address (argument=\"address\", value=\"0x0\", code=INVALID_ARGUMENT, version=address/5.4.0) (argument=null, value=\"0x0\", code=INVALID_ARGUMENT, version=abi/5.0.7)`

And if i add `'0x0'.padEnd(42)` this error is thrown `Provided address 0x0                                        is invalid, the capitalization checksum test failed, or it's an indirect IBAN address which can't be converted.`

**Comment by dhl** [comment]
Hi @itxtoledo, the correct address to use to get ethers balance is `0x0000000000000000000000000000000000000000`. Ethereum addresses are 160 bits long, so in hex that's 160 bits / 4 bits per hex character = 40 hex characters. That's why you need to pass in 0x followed by 40 0's.

You can get the zero address easily using these 3 ways:

1. Using Ethers.js, you could get the zero address using `ethers.constants.AddressZero`.
2. With pure JS, you could do `'0x'.padEnd(42, '0')`.
3. If you're working with Web3.js, directly, you might want to bring in the library `@openzeppelin/test-helpers` from OpenZeppelin, where they have defined zero address in the `constants` module, e.g. `constants.ZERO_ADDRESS`.

Hope that helps. Good luck!

**Comment by itxtoledo** [comment]
> Hi @itxtoledo, the correct address to use to get ethers balance is `0x0000000000000000000000000000000000000000`. Ethereum addresses are 160 bits long, so in hex that's 160 bits / 4 bits per hex character = 40 hex characters. That's why you need to pass in 0x followed by 40 0's.
> 
> You can get the zero address easily using these 3 ways:
> 
> 1. Using Ethers.js, you could get the zero address using `ethers.constants.AddressZero`.
> 2. With pure JS, you could do `'0x'.padEnd(42, '0')`.
> 3. If you're working with Web3.js, directly, you might want to bring in the library `@openzeppelin/test-helpers` from OpenZeppelin, where they have defined zero address in the `constants` module, e.g. `constants.ZERO_ADDRESS`.
> 
> Hope that helps. Good luck!

Thx, worked
